import psycopg2

conn = psycopg2.connect(database="postgres", user="postgres", password="testPassword", host="127.0.0.1", port="5432")

conn.autocommit = True

cursor = conn.cursor()

sql = '''
    CREATE DATABASE pigeonhole;
'''

cursor.execute(sql)
conn.close 

conn = psycopg2.connect(database="pigeonhole", user="postgres", password="testPassword", host="127.0.0.1", port="5432")
conn.autocommit = True
cursor = conn.cursor()

sql = '''
    CREATE EXTENSION pgcrypto;

    CREATE TYPE game AS ENUM ('clicker', 'shooter','fbi');

    CREATE TABLE players(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username text UNIQUE NOT NULL,
        password text NOT NULL
    );

    CREATE TABLE pigeonholes(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        player_id integer REFERENCES players(id) ON DELETE CASCADE,
        position integer,
        UNIQUE (player_id, position)
    );

    CREATE TABLE pigeons(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        owner_id integer REFERENCES players(id) ON DELETE CASCADE,
        pigeonhole_id integer UNIQUE REFERENCES pigeonholes(id) ON DELETE SET NULL (pigeonhole_id),
        state text,
        chance integer,
        intelligence integer,
        constitution integer
    );

    CREATE TABLE hats(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        price double precision CHECK (price > 0),
        img_name text
    );

    CREATE TABLE highscore(
        user_id integer REFERENCES players(id) ON DELETE CASCADE,
        game game,
        score integer,
        score_time timestamp,
        PRIMARY KEY (user_id, game) 
    );

    CREATE TABLE wears(
        pigeon integer REFERENCES pigeons(id) ON DELETE CASCADE,
        hat integer REFERENCES hats(id) ON DELETE CASCADE,
        PRIMARY KEY (pigeon, hat)
    );

    CREATE TABLE owns(
        player_id integer REFERENCES players(id) ON DELETE CASCADE,
        hat integer REFERENCES hats(id) ON DELETE CASCADE,
        amount integer CHECK (amount > 0),
        PRIMARY KEY (player_id, hat)
    );

    CREATE OR REPLACE FUNCTION public.get_pigeon_by_id(_id integer)
    RETURNS pigeons
    LANGUAGE sql
    AS $function$
    SELECT * FROM pigeons WHERE id = _id LIMIT 1;
    $function$

    CREATE OR REPLACE PROCEDURE public.set_score(IN _id integer, IN _game game, IN _score integer)
    LANGUAGE plpgsql
    AS $procedure$
    BEGIN
        IF EXISTS( SELECT * FROM highscore WHERE game = _game AND user_id = _id) THEN
            UPDATE highscore 
            SET score = _score 
            WHERE game = _game AND user_id = _id;
        ELSE
            INSERT INTO highscore (user_id, game, score, created_at) 
            VALUES (_id, _game, _score, current_timestamp);
        END IF;
    END;
    $procedure$
'''

cursor.execute(sql)

conn.close 