import psycopg2

conn = psycopg2.connect(database="postgres", user="postgres", password="testPassword", host="127.0.0.1", port="5432")

conn.autocommit = True

cursor = conn.cursor()

sql = '''
    CREATE DATABASE pigeonhole;
'''

cursor.execute(sql)
conn.close 

conn = psycopg2.connect(database="pigeonhole", user="postgres", password="testPassword", host="127.0.0.1", port="5432")
conn.autocommit = True
cursor = conn.cursor()

sql = '''
    CREATE EXTENSION pgcrypto;

    CREATE TYPE game AS ENUM ('clicker', 'shooter','fbi');

    CREATE TABLE players(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username text UNIQUE NOT NULL,
        password text NOT NULL
    );

    CREATE TABLE pigeonholes(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        player_id integer REFERENCES players(id),
        position integer,
        UNIQUE (player_id, position)
    );

    CREATE TABLE pigeons(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        owner_id integer REFERENCES players(id),
        pigeonhole_id integer UNIQUE REFERENCES pigeonholes(id),
        state text,
        chance integer,
        intelligence integer,
        constitution integer
    );

    CREATE TABLE hats(
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        price double precision,
        img_name text
    );

    CREATE TABLE highscore(
        user_id integer REFERENCES players(id),
        game game,
        score integer,
        score_time timestamp,
        PRIMARY KEY (user_id, game) 
    );

    CREATE TABLE wears(
        pigeon integer REFERENCES pigeons(id),
        hat integer REFERENCES hats(id),
        PRIMARY KEY (pigeon, hat)
    );

    CREATE TABLE owns(
        player_id integer REFERENCES players(id),
        hat integer REFERENCES hats(id),
        amount integer,
        PRIMARY KEY (player_id, hat)
    );
'''

cursor.execute(sql)

conn.close 